from html import escape
from fastapi import FastAPI
from fastapi.responses import HTMLResponse
from .report import build_report
app=FastAPI(title='InfraGuard AI',version='0.1.0',description='Critical-infrastructure AI assurance and resilience simulation')
@app.get('/healthz')
def healthz(): return {'status':'ok','service':'infraguard-ai'}
@app.get('/report')
def report(): return build_report()
@app.get('/scenarios')
def scenarios(): return build_report()['scenarios']
@app.get('/decisions')
def decisions(): return build_report()['decisions']
@app.get('/provenance')
def provenance(): return build_report()['provenance']
@app.get('/',response_class=HTMLResponse)
def home():
    r=build_report(); s=r['summary']; c=r['components']
    cards=''.join(f"<div class='card'><span>{escape(k.replace('_',' ').title())}</span><strong>{v:.1f}</strong><div class='bar'><i style='width:{v:.1f}%'></i></div></div>" for k,v in c.items())
    scen=''.join(f"<tr><td><b>{escape(x['name'])}</b><small>{escape(x['category'])}</small></td><td>{x['severity']}/5</td><td>{x['detect_seconds']}s</td><td>{x['contain_seconds']}s</td><td>{x['recover_seconds']}s</td><td><em>CONTAINED</em></td></tr>" for x in r['scenarios'])
    dec=''.join(f"<tr><td>{escape(x['action_id'])}</td><td><b>{escape(x['decision'])}</b></td><td>{x['risk_score']}</td><td>{escape('; '.join(x['reasons']))}</td></tr>" for x in r['decisions'])
    prov=''.join(f"<tr><td>{escape(x['artifact_id'])}</td><td>{escape(x['artifact_type'])}</td><td>{escape(x['source'])}</td><td><em class='{'ok' if x['verified'] else 'bad'}'>{'VERIFIED' if x['verified'] else 'MISMATCH'}</em></td></tr>" for x in r['provenance'])
    html="""<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>InfraGuard AI</title><style>
    :root{--bg:#071019;--panel:#0d1926;--line:#243a4b;--text:#edf5f7;--muted:#96aab5;--cyan:#50d5c8;--blue:#68a7ff;--amber:#f5bd61;--red:#ff7183}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 80% 0,#102a35,transparent 32%),#071019;color:var(--text);font-family:Inter,system-ui,sans-serif}.wrap{max-width:1200px;margin:auto;padding:0 24px 52px}header{padding:22px 0;border-bottom:1px solid var(--line);font-weight:800}.hero{display:grid;grid-template-columns:1.25fr .75fr;gap:24px;padding:48px 0 30px}.eyebrow{color:var(--cyan);font-size:11px;letter-spacing:.16em;text-transform:uppercase;font-weight:800}h1{font-size:58px;line-height:1;letter-spacing:-.05em;margin:10px 0 16px}.hero p{color:#b9c9d0;line-height:1.65}.mission{background:var(--panel);border:1px solid var(--line);border-radius:18px;padding:24px}.score{font-size:56px;font-weight:900}.score small{font-size:18px;color:var(--muted)}.kpis,.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.grid{grid-template-columns:repeat(3,1fr)}.kpi,.card{background:var(--panel);border:1px solid var(--line);border-radius:15px;padding:18px}.kpi span,.card span{display:block;color:var(--muted);font-size:10px;text-transform:uppercase;letter-spacing:.08em}.kpi strong,.card strong{display:block;font-size:28px;margin-top:7px}.bar{height:5px;background:#1a3140;border-radius:8px;overflow:hidden;margin-top:9px}.bar i{display:block;height:100%;background:linear-gradient(90deg,var(--blue),var(--cyan))}section{margin-top:38px}h2{font-size:24px}.table{overflow:auto;border:1px solid var(--line);border-radius:15px}table{width:100%;border-collapse:collapse;background:var(--panel)}th,td{padding:12px;border-bottom:1px solid #1b3140;text-align:left;font-size:12px}th{color:#78909e;font-size:10px;text-transform:uppercase;background:#0a1621}td{color:#bfd0d7}td small{display:block;color:#718995;margin-top:3px}em{font-style:normal;font-size:10px;font-weight:800;color:#65e1aa}.bad{color:#ff8b99}.callout{border-left:3px solid var(--amber);background:rgba(245,189,97,.05);padding:15px 18px;margin-top:28px;color:#bccbd1}@media(max-width:850px){.hero{grid-template-columns:1fr}.kpis{grid-template-columns:repeat(2,1fr)}.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:520px){.kpis,.grid{grid-template-columns:1fr}h1{font-size:42px}}
    </style></head><body><div class='wrap'><header>IG &nbsp; InfraGuard AI</header><div class='hero'><div><div class='eyebrow'>Critical infrastructure · AI assurance · resilience</div><h1>Trust the mission, not just the model.</h1><p>Defensive simulation for evaluating AI-assisted decisions in high-consequence IT/OT/ICS-style environments using safety envelopes, provenance, least privilege, human override and degraded-safe control.</p></div><div class='mission'><div class='eyebrow'>Mission resilience score</div><div class='score'>__SCORE__<small>/100</small></div><p>Weighted across detection, containment, recovery, human override, data integrity and operational safety.</p></div></div><div class='kpis'><div class='kpi'><span>Scenarios contained</span><strong>__CONTAINED__</strong></div><div class='kpi'><span>Unsafe actions blocked</span><strong>__BLOCKED__</strong></div><div class='kpi'><span>Provenance health</span><strong>__PROV__</strong></div><div class='kpi'><span>Human override</span><strong>__OVERRIDE__</strong></div></div><section><h2>Mission assurance dimensions</h2><div class='grid'>__CARDS__</div></section><section><h2>Resilience scenarios</h2><div class='table'><table><tr><th>Scenario</th><th>Severity</th><th>Detect</th><th>Contain</th><th>Recover</th><th>Status</th></tr>__SCEN__</table></div></section><section><h2>Runtime safety decisions</h2><div class='table'><table><tr><th>Action</th><th>Decision</th><th>Risk</th><th>Evidence</th></tr>__DEC__</table></div></section><section><h2>AI/data provenance</h2><div class='table'><table><tr><th>Artifact</th><th>Type</th><th>Source</th><th>Status</th></tr>__PROW__</table></div></section><div class='callout'><b>Evaluation boundary.</b> All assets, telemetry, model artifacts, operator actions and scenarios are synthetic. No real PLC, SCADA, utility, defense or critical-infrastructure system is contacted.</div></div></body></html>"""
    return (html.replace('__SCORE__',f"{r['mission_resilience_score']:.1f}").replace('__CONTAINED__',f"{s['contained']}/{s['scenarios']}").replace('__BLOCKED__',str(s['unsafe_actions_blocked'])).replace('__PROV__',f"{r['provenance_health']:.0%}").replace('__OVERRIDE__',f"{s['human_override_success']}/{s['human_override_required']}").replace('__CARDS__',cards).replace('__SCEN__',scen).replace('__DEC__',dec).replace('__PROW__',prov))
